export const images = [
   {
    src: "snacks-with-mountains.webp",
    original: `${process.env.PUBLIC_URL}/snacks-with-mountains.webp`,
    width: 1328,
    height: 1762,
    alt: "Snacks with mountains",
  },
   {
    src: "house_front.webp",
    original: `${process.env.PUBLIC_URL}/house_front.webp`,
    width: 1753,
    height: 1274,
    alt: "Front view of a himachali homestay in manali",
  },
  {
    src: "homestay-outside-view.jpg",
    original: `${process.env.PUBLIC_URL}/homestay-outside-view.jpg`,
    width: 940,
    height: 1830,
    alt: "Outside view of Pahadi Basera homestay",
  },
  {
    src: "happy-guests-in-mountain-home.webp",
    original: `${process.env.PUBLIC_URL}/happy-guests-in-mountain-home.webp`,
    width: 1002,
    height: 1330,
    alt: "Guests in homestay near manali",
  },
  {
    src: "homestay-in-mountains-evening.webp",
    original: `${process.env.PUBLIC_URL}/homestay-in-mountains-evening.webp`,
    width: 1330,
    height: 1002,
    alt: "Evening time at a homestay in mountains",
  }, 
  {
    src: "homestay-food.webp",
    original: `${process.env.PUBLIC_URL}/homestay-food.webp`,
    width: 1002,
    height: 1330,
    alt: "Pure vegetarian homestay food",
  },
  {
    src: "dorm-room-pahadi-basera-homestay.webp",
    original: `${process.env.PUBLIC_URL}/dorm-room-pahadi-basera-homestay.webp`,
    width: 806,
    height: 604,
    alt: "Budget room in katkhuni house in manali",
  },
  {
    src: "mudhouse-bedroom.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-bedroom.webp`,
    width: 1330,
    height: 1002,
    alt: "Room in mudhouse",
  },
  {
    src: "breakfast-with-view.webp",
    original: `${process.env.PUBLIC_URL}/breakfast-with-view.webp`,
    width: 1002,
    height: 1330,
    alt: "Enjoy breakfast with view",
  },
  {
    src: "himachali-common-space.webp",
    original: `${process.env.PUBLIC_URL}/himachali-common-space.webp`,
    width: 1330,
    height: 1002,
    alt: "Common space in a traditional homestay",
  },
  {
    src: "pahadi-basera-evening-view.webp",
    original: `${process.env.PUBLIC_URL}/pahadi-basera-evening-view.webp`,
    width: 1002,
    height: 1330,
    alt: "Best evening view in mountains",
  },
  {
    src: "himachali-common-space1.webp",
    original: `${process.env.PUBLIC_URL}/himachali-common-space1.webp`,
    width: 1330,
    height: 1002,
    alt: "Traditinaly styled Living room of a mudhouse in mountains",
  },
  {
    src: "vegetarian-breakfast-manali.webp",
    original: `${process.env.PUBLIC_URL}/vegetarian-breakfast-manali.webp`,
    width: 1330,
    height: 1002,
    alt: "Homely meals in homestay",
  },
  {
    src: "mudhouse-dining-area.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-dining-area.webp`,
    width: 1002,
    height: 1330,
    alt: "Dining are in mountain home",
  },
  {
    src: "outside-view-around-pahadi-basera.webp",
    original: `${process.env.PUBLIC_URL}/outside-view-around-pahadi-basera.webp`,
    width: 1158,
    height: 980,
    alt: "Outside view of pahadi basera manali",
  },
  {
    src: "kids-enjoying-vacation-in-manali.webp",
    original: `${process.env.PUBLIC_URL}/kids-enjoying-vacation-in-manali.webp`,
    width: 1330,
    height: 1002,
    alt: "Kids Enjoying vacation near manali in Pahadi basera",
  },
  {
    src: "summers-in-mountainhome.webp",
    original: `${process.env.PUBLIC_URL}/summers-in-mountainhome.webp`,
    width: 1330,
    height:1002 ,
    alt: "Summers in a mudhouse in mountains",
  },
  {
    src: "kathkuni-homestay-hostel-style-room.webp",
    original: `${process.env.PUBLIC_URL}/kathkuni-homestay-hostel-style-room.webp`,
    width: 1002,
    height:1330 ,
    alt: "Hostel room in a tradtional house near manali",
  },
  {
    src: "happytime-in-mudhouse.webp",
    original: `${process.env.PUBLIC_URL}/happytime-in-mudhouse.webp`,
    width: 1002,
    height: 1330,
    alt: "Happy time wuth guest in mudhouse",
  },
  {
    src: "mudhouse-private-room-window.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-private-room-window.webp`,
    width: 1002,
    height: 1330,
    alt: "Private room in Pahadi basera homestay near manali",
  },
  
  {
    src: "guest-under-cloudy-night-sky-homestay.webp",
    original: `${process.env.PUBLIC_URL}/guest-under-cloudy-night-sky-homestay.webp`,
    width: 1330,
    height: 1002,
    alt: "Guest undler cloudy night sky in manali homestay",
  },
  {
    src: "guest-relaxing-in-mountain-homestay.webp",
    original: `${process.env.PUBLIC_URL}/guest-relaxing-in-mountain-homestay.webp`,
    width: 1002,
    height: 1330,
    alt: "Guest relaxing in mountains with view",
  },
  {
    src: "mudhouse-privateroom.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-privateroom.webp`,
    width: 1330,
    height:1002 ,
    alt: "Private room in mudhouse in manali",
  },
  {
    src: "sunset-view-mudhouse-manali.webp",
    original: `${process.env.PUBLIC_URL}/sunset-view-mudhouse-manali.webp`,
    width: 1330,
    height: 1002,
    alt: "Sunset view of mudhouse in manali",
  },
]
