export const images = [
   {
    src: "snacks-with-mountains.webp",
    original: `${process.env.PUBLIC_URL}/snacks-with-mountains.webp`,
    width: 1328,
    height: 1762,
  },
   {
    src: "house_front.webp",
    original: `${process.env.PUBLIC_URL}/house_front.webp`,
    width: 1753,
    height: 1274,
  },
  {
    src: "homestay-outside-view.jpg",
    original: `${process.env.PUBLIC_URL}/homestay-outside-view.jpg`,
    width: 940,
    height: 1830,
  },
  {
    src: "happy-guests-in-mountain-home.webp",
    original: `${process.env.PUBLIC_URL}/happy-guests-in-mountain-home.webp`,
    width: 1002,
    height: 1330,
  },
 
  {
    src: "homestay-in-mountains-evening.webp",
    original: `${process.env.PUBLIC_URL}/homestay-in-mountains-evening.webp`,
    width: 1330,
    height: 1002,
  }, 
  {
    src: "homestay-food.webp",
    original: `${process.env.PUBLIC_URL}/homestay-food.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "dorm-room-pahadi-basera-homestay.webp",
    original: `${process.env.PUBLIC_URL}/dorm-room-pahadi-basera-homestay.webp`,
    width: 806,
    height: 604,
  },
  {
    src: "mudhouse-bedroom.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-bedroom.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "breakfast-with-view.webp",
    original: `${process.env.PUBLIC_URL}/breakfast-with-view.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "himachali-common-space.webp",
    original: `${process.env.PUBLIC_URL}/himachali-common-space.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "pahadi-basera-evening-view.webp",
    original: `${process.env.PUBLIC_URL}/pahadi-basera-evening-view.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "himachali-common-space1.webp",
    original: `${process.env.PUBLIC_URL}/himachali-common-space1.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "vegetarian-breakfast-manali.webp",
    original: `${process.env.PUBLIC_URL}/vegetarian-breakfast-manali.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "mudhouse-dining-area.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-dining-area.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "outside-view-around-pahadi-basera.webp",
    original: `${process.env.PUBLIC_URL}/outside-view-around-pahadi-basera.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "kids-enjoying-vacation-in-manali.webp",
    original: `${process.env.PUBLIC_URL}/kids-enjoying-vacation-in-manali.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "summers-in-mountainhome.webp",
    original: `${process.env.PUBLIC_URL}/summers-in-mountainhome.webp`,
    width: 1330,
    height:1002 ,
  },
  {
    src: "kathkuni-homestay-hostel-style-room.webp",
    original: `${process.env.PUBLIC_URL}/kathkuni-homestay-hostel-style-room.webp`,
    width: 1002,
    height:1330 ,
  },
  {
    src: "happytime-in-mudhouse.webp",
    original: `${process.env.PUBLIC_URL}/happytime-in-mudhouse.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "mudhouse-private-room-window.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-private-room-window.webp`,
    width: 1002,
    height: 1330,
  },
  
  {
    src: "guest-under-cloudy-night-sky-homestay.webp",
    original: `${process.env.PUBLIC_URL}/guest-under-cloudy-night-sky-homestay.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "guest-relaxing-in-mountain-homestay.webp",
    original: `${process.env.PUBLIC_URL}/guest-relaxing-in-mountain-homestay.webp`,
    width: 1002,
    height: 1330,
  },
  {
    src: "mudhouse-privateroom.webp",
    original: `${process.env.PUBLIC_URL}/mudhouse-privateroom.webp`,
    width: 1330,
    height:1002 ,
  },
  {
    src: "sunset-view-mudhouse-manali.webp",
    original: `${process.env.PUBLIC_URL}/sunset-view-mudhouse-manali.webp`,
    width: 1330,
    height: 1002,
  },
]
