export const images = [
  {
    src: "winteroutside2.webp",
    original: `${process.env.PUBLIC_URL}/winteroutside2.webp`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside1.webp",
    original: `${process.env.PUBLIC_URL}/winteroutside1.webp`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside3.webp",
    original: `${process.env.PUBLIC_URL}/winteroutside3.webp`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside4.webp",
    original: `${process.env.PUBLIC_URL}/outside3.webp`,
    width: 1158,
    height: 980,
  }, 
  {
    src: "economyroom.webp",
    original: `${process.env.PUBLIC_URL}/economyroom.webp`,
    width: 4032,
    height: 3024,
  },
  {
    src: "food1.webp",
    original: `${process.env.PUBLIC_URL}/food1.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "hostelroom2.webp",
    original: `${process.env.PUBLIC_URL}/hostelroom2.webp`,
    width: 4032,
    height: 3024,
  },
  {
    src: "food2.webp",
    original: `${process.env.PUBLIC_URL}/food2.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "bedroom1.webp",
    original: `${process.env.PUBLIC_URL}/bedroom1.webp`,
    width: 4032,
    height: 3024,
  },
  {
    src: "hall2.webp",
    original: `${process.env.PUBLIC_URL}/hall2.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "outside2.webp",
    original: `${process.env.PUBLIC_URL}/outside2.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall.webp",
    original: `${process.env.PUBLIC_URL}/hall.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall3.webp",
    original: `${process.env.PUBLIC_URL}/hall3.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "outside3.webp",
    original: `${process.env.PUBLIC_URL}/outside3.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "hostelroom.webp",
    original: `${process.env.PUBLIC_URL}/hostelroom.webp`,
    width: 4032,
    height:3024 ,
  },
  {
    src: "guests1.webp",
    original: `${process.env.PUBLIC_URL}/guests1.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall4.webp",
    original: `${process.env.PUBLIC_URL}/hall4.webp`,
    width: 1158,
    height: 980,
  },
  
  {
    src: "night.webp",
    original: `${process.env.PUBLIC_URL}/night.webp`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside5.webp",
    original: `${process.env.PUBLIC_URL}/winteroutside5.webp`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside6.webp",
    original: `${process.env.PUBLIC_URL}/winteroutside6.webp`,
    width: 1158,
    height: 980,
  },
]
