export const images = [
   {
    src: "food4.webp",
    original: `${process.env.PUBLIC_URL}/food4.webp`,
    width: 1328,
    height: 1762,
  },
   {
    src: "house_front.webp",
    original: `${process.env.PUBLIC_URL}/house_front.webp`,
    width: 1753,
    height: 1274,
  },
  {
    src: "home1.jpg",
    original: `${process.env.PUBLIC_URL}/home.jpg`,
    width: 940,
    height: 1830,
  },
  {
    src: "guests2.webp",
    original: `${process.env.PUBLIC_URL}/guests2.webp`,
    width: 1002,
    height: 1330,
  },
 
  {
    src: "out_evening1.webp",
    original: `${process.env.PUBLIC_URL}/out_evening1.webp`,
    width: 1330,
    height: 1002,
  }, 
  {
    src: "food1.webp",
    original: `${process.env.PUBLIC_URL}/food1.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "hostelroom2.webp",
    original: `${process.env.PUBLIC_URL}/hostelroom2.webp`,
    width: 806,
    height: 604,
  },
  {
    src: "bedroom1.webp",
    original: `${process.env.PUBLIC_URL}/bedroom1.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "food2.webp",
    original: `${process.env.PUBLIC_URL}/food2.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "hall2.webp",
    original: `${process.env.PUBLIC_URL}/hall2.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "outside1.webp",
    original: `${process.env.PUBLIC_URL}/outside1.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "hall.webp",
    original: `${process.env.PUBLIC_URL}/hall.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "food3.webp",
    original: `${process.env.PUBLIC_URL}/food3.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "hall3.webp",
    original: `${process.env.PUBLIC_URL}/hall3.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "outside3.webp",
    original: `${process.env.PUBLIC_URL}/outside3.webp`,
     width: 1158,
    height: 980,
  },
  {
    src: "guests5.webp",
    original: `${process.env.PUBLIC_URL}/guests5.webp`,
     width: 1330,
    height: 1002,
  },
  {
    src: "home.webp",
    original: `${process.env.PUBLIC_URL}/home.webp`,
    width: 1330,
    height:1002 ,
  },
  {
    src: "hostelroom.webp",
    original: `${process.env.PUBLIC_URL}/hostelroom.webp`,
    width: 1002,
    height:1330 ,
  },
  {
    src: "guests3.webp",
    original: `${process.env.PUBLIC_URL}/guests3.webp`,
     width: 1002,
    height: 1330,
  },
  {
    src: "roomwindow.webp",
    original: `${process.env.PUBLIC_URL}/roomwindow.webp`,
    width: 1002,
    height: 1330,
  },
  
  {
    src: "night.webp",
    original: `${process.env.PUBLIC_URL}/night.webp`,
    width: 1330,
    height: 1002,
  },
  {
    src: "outside.webp",
    original: `${process.env.PUBLIC_URL}/outside.webp`,
    width: 1002,
    height: 1330,
  },
  {
    src: "economyroom.webp",
    original: `${process.env.PUBLIC_URL}/economyroom.webp`,
    width: 1330,
    height:1002 ,
  },
  {
    src: "hero1.webp",
    original: `${process.env.PUBLIC_URL}/hero1.webp`,
    width: 1330,
    height: 1002,
  },
]
